algoritmo "contadorAgoraVai"
var
   contador, valor, salto, soma: inteiro
inicio
   Escreva ("Quer contar até quanto? ")
   Leia (valor)
   EscrevaL ("E qual o salto? ")
   Leia (salto)
   contador <- 0
   Enquanto (contador <= valor) faca
      EscrevaL (contador)
      contador <- contador + salto
   FimEnquanto
   Escreva ("Agora vou somar estes números! ")
   soma <-
fimalgoritmo